version: '3.8'
services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
      volumes:
        - "postgres:/var/lib/postgresql/data"
      ports:
        - "5432:5432"
    mongodb_container:
      image: mongo:latest
      environment:
        MONGO_INITDB_USERNAME: mongo
        MONGO_INITDB_PASSWORD: mongo
        MONGO_INITDB_DATABASE: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
volumes:
  postgres:
  mongodb_data_container:



